### ISSUE TITLE
Issue in Lab 3 - Request for Preprocessed Dataset

### ISSUE THREAD

**Issue by quansi0817** [HROlive/Applications-of-AI-for-Anomaly-Detection#1]
Hello,

Thank you for sharing this valuable code!

In Lab 3, I’m getting errors when training the GAN model. I’ve tried nearly all preprocessed data from Labs 1 and 2, but I still can’t match your results.

Could you please share the exact preprocessed dataset used for Lab 3? It would really help.

Thank you so much!!

**Comment by HROlive** [comment]
Hello,

I've uploaded the available datasets to the repository https://github.com/HROlive/Applications-of-AI-for-Anomaly-Detection/blob/main/data.tar.gz

Hope this helps!
